port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: https://github.com/Alvin9999/new-pac/wiki ip, server: 162.159.138.245, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 2, server: 172.67.127.123, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 3, server: 103.21.244.39, port: 443, type: vmess, uuid: efb8f3ba-848f-4716-b233-ea038cd2eb32, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /qwer, headers: {Host: vtcss.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 4, server: 64.32.4.53, port: 42175, type: vmess, uuid: 8653004f-de67-44c2-9cce-e0830933fb03, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 5, server: 172.64.173.160, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: ca.ilovescp.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 6, server: 108.162.193.127, port: 443, type: vmess, uuid: efb8f3ba-848f-4716-b233-ea038cd2eb32, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /qwer, headers: {Host: vtcss.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 7, server: 172.67.86.87, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 8, server: 172.67.217.222, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp3.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 9, server: 172.67.87.132, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 10, server: cf-lt.sharecentre.online, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: ca.ilovescp.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 11, server: 172.67.98.34, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 12, server: 192.74.231.172, port: 49202, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 13, server: 45.131.229.56, port: 41602, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 14, server: 192.74.232.248, port: 51802, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 15, server: 107.148.195.17, port: 50014, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 16, server: 108.186.192.251, port: 35502, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 17, server: 137.175.52.18, port: 33002, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 18, server: 45.64.22.56, port: 443, type: trojan, password: !<str> 123456, sni: trojan-ctb-sg02.globalssh.xyz}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 19, server: vjp1.0bad.com, port: 443, type: vmess, uuid: 927094d3-d678-4763-8591-e240d0bcae87, alterId: 0, cipher: auto, tls: true, servername: vjp1.0bad.com, network: ws, ws-opts: {path: /chat, headers: {Host: vjp1.0bad.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 20, server: rajasa.nirezzvpn.my.id, port: 80, type: vmess, uuid: de815d15-dc94-4aa2-bb9b-207f88339601, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: rajasa.nirezzvpn.my.id}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 21, server: n1681962783.aqdisrv.cn, port: 443, type: vmess, uuid: 3b479e82-ec0c-4ea7-add4-ab2c57d243c9, alterId: 0, cipher: auto, tls: true, servername: n1681962783.aqdisrv.cn, network: ws, ws-opts: {path: /, headers: {Host: n1681962783.aqdisrv.cn}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 22, server: 172.67.57.22, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 23, server: 172.67.250.239, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp2.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 24, server: 192.74.228.171, port: 42857, type: vmess, uuid: 051b844f-efe3-4847-92aa-66b5de0b6d4e, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 25, server: 108.162.192.12, port: 443, type: vmess, uuid: efb8f3ba-848f-4716-b233-ea038cd2eb32, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /qwer, headers: {Host: vtcss.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 26, server: 104.17.3.81, port: 80, type: vmess, uuid: e40b2de3-b829-4591-a7b6-99d1913f3246, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /worryfree, headers: {Host: w.evouch77.live}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 27, server: 25.v2-ray.cyou, port: 23625, type: vmess, uuid: 0dd19d20-ec86-3680-b256-87237bafa89e, alterId: 2, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: 25.v2-ray.cyou}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 28, server: 172.67.84.93, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 29, server: 172.67.113.82, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 30, server: 198.41.220.47, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: lv3.sharecentrepro.org}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 31, server: 172.67.199.253, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - https://github.com/Alvin9999/new-pac/wiki ip
      - https://github.com/Alvin9999/new-pac/wiki ip 2
      - https://github.com/Alvin9999/new-pac/wiki ip 3
      - https://github.com/Alvin9999/new-pac/wiki ip 4
      - https://github.com/Alvin9999/new-pac/wiki ip 5
      - https://github.com/Alvin9999/new-pac/wiki ip 6
      - https://github.com/Alvin9999/new-pac/wiki ip 7
      - https://github.com/Alvin9999/new-pac/wiki ip 8
      - https://github.com/Alvin9999/new-pac/wiki ip 9
      - https://github.com/Alvin9999/new-pac/wiki ip 10
      - https://github.com/Alvin9999/new-pac/wiki ip 11
      - https://github.com/Alvin9999/new-pac/wiki ip 12
      - https://github.com/Alvin9999/new-pac/wiki ip 13
      - https://github.com/Alvin9999/new-pac/wiki ip 14
      - https://github.com/Alvin9999/new-pac/wiki ip 15
      - https://github.com/Alvin9999/new-pac/wiki ip 16
      - https://github.com/Alvin9999/new-pac/wiki ip 17
      - https://github.com/Alvin9999/new-pac/wiki ip 18
      - https://github.com/Alvin9999/new-pac/wiki ip 19
      - https://github.com/Alvin9999/new-pac/wiki ip 20
      - https://github.com/Alvin9999/new-pac/wiki ip 21
      - https://github.com/Alvin9999/new-pac/wiki ip 22
      - https://github.com/Alvin9999/new-pac/wiki ip 23
      - https://github.com/Alvin9999/new-pac/wiki ip 24
      - https://github.com/Alvin9999/new-pac/wiki ip 25
      - https://github.com/Alvin9999/new-pac/wiki ip 26
      - https://github.com/Alvin9999/new-pac/wiki ip 27
      - https://github.com/Alvin9999/new-pac/wiki ip 28
      - https://github.com/Alvin9999/new-pac/wiki ip 29
      - https://github.com/Alvin9999/new-pac/wiki ip 30
      - https://github.com/Alvin9999/new-pac/wiki ip 31
rules:
 - MATCH,🔰 节点选择
