port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: https://github.com/Alvin9999/new-pac/wiki ip, server: a16.achenxty.top, port: 11616, type: vmess, uuid: abfe3178-3f19-32cd-95b2-5ad2dd39bce6, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 2, server: catlog.flareai.science, port: 15543, type: ss, cipher: chacha20-ietf-poly1305, password: d5dd371c-11db-4cfb-b458-072f0fbd0e18}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 3, server: catlog.flareai.science, port: 15443, type: ss, cipher: chacha20-ietf-poly1305, password: d5dd371c-11db-4cfb-b458-072f0fbd0e18}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 4, server: 25.v2-ray.cyou, port: 23625, type: vmess, uuid: 0dd19d20-ec86-3680-b256-87237bafa89e, alterId: 2, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: 25.v2-ray.cyou}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 5, server: a21.achenxty.top, port: 11621, type: vmess, uuid: abfe3178-3f19-32cd-95b2-5ad2dd39bce6, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 6, server: a12.achenxty.top, port: 11612, type: vmess, uuid: abfe3178-3f19-32cd-95b2-5ad2dd39bce6, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 7, server: assets.flareai.site, port: 15343, type: ss, cipher: chacha20-ietf-poly1305, password: d5dd371c-11db-4cfb-b458-072f0fbd0e18}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 8, server: sz.cny.page, port: 11536, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 9, server: sz.cny.page, port: 32366, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 10, server: sz.cny.page, port: 25984, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 11, server: hbct2.qq.com.qqcdnxb.com, port: 18000, type: vmess, uuid: 7bae1ccc-8091-4f26-b22a-14857e8fde3d, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 12, server: 222.222.8.164, port: 18000, type: vmess, uuid: 7bae1ccc-8091-4f26-b22a-14857e8fde3d, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 13, server: data-hk-v1.shwjfkw.cn, port: 50207, type: vmess, uuid: b1478e24-4916-3abe-8f17-15931012ecbe, alterId: 1, cipher: auto, tls: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: YTB-awkj}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 14, server: cf-lt.sharecentre.online, port: 80, type: vmess, uuid: 35d1eaf8-53e7-4c8b-92aa-d96a20854e3c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /api/v3/download.getFile, headers: {Host: ssrsub.v01.ssrsub.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 15, server: 67.21.89.136, port: 46866, type: vmess, uuid: b697d727-cf6c-41dd-a0de-c7a9478e4a4a, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 16, server: 107.167.7.12, port: 41654, type: vmess, uuid: bdee202c-8fae-441f-a588-7bc4d3887019, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 17, server: jp80.fee68414a14e.sanfen004.me, port: 80, type: vmess, uuid: 692bffe9-01b7-4e0b-aa44-bbba867d67e1, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /zh-cn, headers: {Host: jp80.fee68414a14e.sanfen004.me}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 18, server: cdn.gcup.wiki, port: 2053, type: vmess, uuid: da12affb-2953-4b35-9677-f85d9743d9c4, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /freegcup, headers: {Host: kr.gcup.wiki}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 19, server: v3.erciyun.men, port: 1011, type: vmess, uuid: edd2b1bb-e74b-4d0e-81c3-baff279de1a0, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /obb, headers: {Host: v3.erciyun.men}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 20, server: cdn.alibaba-kunlun.com, port: 14113, type: ss, cipher: aes-128-gcm, password: ed53251d-83eb-43fa-9439-b1bc45bf7ca3}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 21, server: mci.bamarambash.monster, port: 443, type: vmess, uuid: 8f74ec8a-971c-11ed-a8fc-0242ac120002, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /db698b16-d216-11ed-8e14-5ad705867cff, headers: {Host: db698b16-d216-11ed-8e14-5ad705867cff.asmandll.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 22, server: rajasa.nirezzvpn.my.id, port: 80, type: vmess, uuid: de815d15-dc94-4aa2-bb9b-207f88339601, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /vmessws, headers: {Host: rajasa.nirezzvpn.my.id}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 23, server: a14.achenxty.top, port: 11614, type: vmess, uuid: abfe3178-3f19-32cd-95b2-5ad2dd39bce6, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 24, server: ah-cm.cmcclives.top, port: 58469, type: vmess, uuid: 8e328e84-2845-4f13-b521-78ddb79c9f3b, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 25, server: 140.99.59.253, port: 55512, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 26, server: 192.74.228.171, port: 42857, type: vmess, uuid: 051b844f-efe3-4847-92aa-66b5de0b6d4e, alterId: 64, cipher: auto, tls: false, servername: n1674862929.gofdwgy.cn}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 27, server: 38.40.158.245, port: 45002, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 28, server: 192.74.228.171, port: 42857, type: vmess, uuid: 051b844f-efe3-4847-92aa-66b5de0b6d4e, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 29, server: 25.v2-ray.cyou, port: 23625, type: vmess, uuid: 0dd19d20-ec86-3680-b256-87237bafa89e, alterId: 2, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: 25.v2-ray.cyou}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 30, server: 172.67.127.123, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 31, server: 172.64.173.160, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: ca.ilovescp.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 32, server: cf-lt.sharecentre.online, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: ca.ilovescp.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 33, server: 104.17.3.81, port: 80, type: vmess, uuid: e40b2de3-b829-4591-a7b6-99d1913f3246, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /worryfree, headers: {Host: w.evouch77.live}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 34, server: 192.74.231.172, port: 49202, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 35, server: vjp1.0bad.com, port: 443, type: vmess, uuid: 927094d3-d678-4763-8591-e240d0bcae87, alterId: 0, cipher: auto, tls: true, servername: vjp1.0bad.com, network: ws, ws-opts: {path: /chat, headers: {Host: vjp1.0bad.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 36, server: 172.67.217.222, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp3.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 37, server: 198.41.220.47, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: lv3.sharecentrepro.org}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 38, server: 172.67.250.239, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp2.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 39, server: 45.64.22.56, port: 443, type: trojan, password: !<str> 123456, sni: trojan-ctb-sg02.globalssh.xyz}
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - https://github.com/Alvin9999/new-pac/wiki ip
      - https://github.com/Alvin9999/new-pac/wiki ip 2
      - https://github.com/Alvin9999/new-pac/wiki ip 3
      - https://github.com/Alvin9999/new-pac/wiki ip 4
      - https://github.com/Alvin9999/new-pac/wiki ip 5
      - https://github.com/Alvin9999/new-pac/wiki ip 6
      - https://github.com/Alvin9999/new-pac/wiki ip 7
      - https://github.com/Alvin9999/new-pac/wiki ip 8
      - https://github.com/Alvin9999/new-pac/wiki ip 9
      - https://github.com/Alvin9999/new-pac/wiki ip 10
      - https://github.com/Alvin9999/new-pac/wiki ip 11
      - https://github.com/Alvin9999/new-pac/wiki ip 12
      - https://github.com/Alvin9999/new-pac/wiki ip 13
      - https://github.com/Alvin9999/new-pac/wiki ip 14
      - https://github.com/Alvin9999/new-pac/wiki ip 15
      - https://github.com/Alvin9999/new-pac/wiki ip 16
      - https://github.com/Alvin9999/new-pac/wiki ip 17
      - https://github.com/Alvin9999/new-pac/wiki ip 18
      - https://github.com/Alvin9999/new-pac/wiki ip 19
      - https://github.com/Alvin9999/new-pac/wiki ip 20
      - https://github.com/Alvin9999/new-pac/wiki ip 21
      - https://github.com/Alvin9999/new-pac/wiki ip 22
      - https://github.com/Alvin9999/new-pac/wiki ip 23
      - https://github.com/Alvin9999/new-pac/wiki ip 24
      - https://github.com/Alvin9999/new-pac/wiki ip 25
      - https://github.com/Alvin9999/new-pac/wiki ip 26
      - https://github.com/Alvin9999/new-pac/wiki ip 27
      - https://github.com/Alvin9999/new-pac/wiki ip 28
      - https://github.com/Alvin9999/new-pac/wiki ip 29
      - https://github.com/Alvin9999/new-pac/wiki ip 30
      - https://github.com/Alvin9999/new-pac/wiki ip 31
      - https://github.com/Alvin9999/new-pac/wiki ip 32
      - https://github.com/Alvin9999/new-pac/wiki ip 33
      - https://github.com/Alvin9999/new-pac/wiki ip 34
      - https://github.com/Alvin9999/new-pac/wiki ip 35
      - https://github.com/Alvin9999/new-pac/wiki ip 36
      - https://github.com/Alvin9999/new-pac/wiki ip 37
      - https://github.com/Alvin9999/new-pac/wiki ip 38
      - https://github.com/Alvin9999/new-pac/wiki ip 39
rules:
 - MATCH,🔰 节点选择
