port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-5, server: 198.41.203.6, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-4, server: 141.101.115.100, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-3, server: 198.41.212.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-20, server: 185.162.228.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-2, server: 141.101.114.111, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-19, server: 66.235.200.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-18, server: 203.24.108.8, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-17, server: 203.30.188.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr1.v2ray5.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-16, server: 203.30.189.2, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-15, server: 203.30.190.2, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-14, server: 23.227.38.38, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-13, server: 188.114.99.9, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-12, server: 203.30.191.2, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1, server: 141.101.115.111, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-5
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-4
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-3
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-20
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-2
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-19
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-18
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-17
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-16
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-15
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-14
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-13
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1-12
      - 🇫🇷 https://github.com/Alvin9999/new-pac/wiki clash ip5 法国CDN1
rules:
 - MATCH,🔰 节点选择
